version: '3'

services:
  postgres_user:
    container_name: user_db
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    networks:
      - user_net
    volumes:
      - user_db_vol:/var/lib/postgresql/data
  user_management:
    build:
      context: ./user_management
    depends_on:
      - postgres_user
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: user_db
    ports:
      - "3000:3000"
    networks:
      - user_net
      - app_net  



networks:
  user_net:
  post_net:
  route_net:
  offer_net:
  app_net:

volumes:
  user_db_vol:
  post_db_vol:
  route_db_vol:
  offer_db_vol: