version: '3'

services:
  postgres_cinco:
    container_name: cinco_db
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    networks:
      - cinco_net
    volumes:
      - cinco_db_vol:/var/lib/postgresql/data
  cinco_management:
    build:
      context: ./post_ref005_management
    depends_on:
      - postgres_cinco
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: cinco_db
    ports:
      - "3006:3006"
    networks:
      - cinco_net
      - app_net  

networks:
  cinco_net:
  app_net:

volumes:
  cinco_db_vol: